nginx:
  image: jwilder/nginx-proxy:0.6.0
  container_name: nginx-proxy
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro
    - ./certs:/etc/nginx/certs
  ports:
    - 80:80 
    - 443:443 
  restart: always 

